package com.jiuji.cn.business.spcontact.model;


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TProduct generated by hbm2java
 */
@Entity 
public class SpContact implements java.io.Serializable {

   
   public String contact_uid;
   
   public String contact_name;
   
   public String contact_tele;
   
   public String contact_address;
   
   public Integer f_productId;
	
	
	public SpContact() {
	}
	
	public SpContact(String contact_name,String contact_tele,String contact_address,Integer f_productId) {
		this.contact_uid = contact_uid;
		this.contact_name = contact_name;
		this.contact_tele = contact_tele;
		this.contact_address = contact_address;
		this.f_productId = f_productId;
	}


	public String getContact_uid() {
		return contact_uid;
	}


	public void setContact_uid(String contact_uid) {
		this.contact_uid = contact_uid;
	}


	public String getContact_name() {
		return contact_name;
	}


	public void setContact_name(String contact_name) {
		this.contact_name = contact_name;
	}


	public String getContact_tele() {
		return contact_tele;
	}


	public void setContact_tele(String contact_tele) {
		this.contact_tele = contact_tele;
	}


	public String getContact_address() {
		return contact_address;
	}


	public void setContact_address(String contact_address) {
		this.contact_address = contact_address;
	}


	public Integer getF_productId() {
		return f_productId;
	}


	public void setF_productId(Integer f_productId) {
		this.f_productId = f_productId;
	} 
	
	
}
